### ISSUE TITLE
Problem with parsing the result

### ISSUE THREAD

**Issue by sdzolkiewicz** [ACE07-Sev/CQM-TSP#1]
Hi, I think there is something wrong with geting result form sampleset. 
For example if you have more than 10 nodes, def containsNumber(value) takes it as 1 and 0 and returns as 0, -1 with results in something like this: "[6, 0, -1]" and i belive it should be "[6,9]".
Have a good day!
![image](https://github.com/ACE07-Sev/CQM-TSP/assets/128418889/06574c85-34e4-4ef0-add0-b870643ed3f5)

**Comment by ACE07-Sev** [comment]
Thank you @szolkiewicz for the issue.

Pardon the delay, I will get on this right away.

**Comment by ACE07-Sev** [comment]
Issue has been fixed. Kindly try now.
